### ISSUE TITLE
Android build 5.2

### ISSUE THREAD

**Issue by allcontentswe** [gtreshchev/RuntimeSpeechRecognizer#8]
1. Unreal 5.1 ~ 5.2
2. Runtime 5.2

Built according to document but print string recognizes "!!!!!!!!!!!!!!!!!!!!!"

**Comment by gtreshchev** [comment]
Did you make sure that the microphone is working? You can test by simply capturing the audio data for 5 seconds, for example, and playing it back: https://github.com/gtreshchev/RuntimeAudioImporter/wiki/4.-Capturable-Sound-Wave
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/69837452/6f7ede00-8d7b-49d2-ad58-de9360b11861)

**Comment by allcontentswe** [comment]
yes mic I even gave him the authority

**Comment by allcontentswe** [comment]
> 마이크가 작동하는지 확인하셨나요? 예를 들어 5초 동안 오디오 데이터를 캡처하고 재생하여 테스트할 수 있습니다. https://github.com/gtreshchev/RuntimeAudioImporter/wiki/4.-Capturable-Sound-Wave ![영상](https://user-images.githubusercontent.com/69837452/245072405-6f7ede00-8d7b-49d2-ad58-de9360b11861.png)

yes, mic I even gave him the authority

**Comment by allcontentswe** [comment]
> Did you make sure that the microphone is working? You can test by simply capturing the audio data for 5 seconds, for example, and playing it back: https://github.com/gtreshchev/RuntimeAudioImporter/wiki/4.-Capturable-Sound-Wave ![image](https://user-images.githubusercontent.com/69837452/245072405-6f7ede00-8d7b-49d2-ad58-de9360b11861.png)

I took this route https://blueprintue.com/blueprint/et6u52bm/

**Comment by gtreshchev** [comment]
If you have the capturable sound wave working, I believe that there is nothing that could go wrong. Just ensure that you capture the audio data correctly, and that you're able to play it back and listen to the captured voice without any issues.

**Comment by allcontentswe** [comment]
> If you have the capturable sound wave working, I believe that there is nothing that could go wrong. Just ensure that you capture the audio data correctly, and that you're able to play it back and listen to the captured voice without any issues.

I see, but the print string comes out normally in the play editor, but after the Android build, even if you activate the microphone, it's done on the mobile screen "!!!!!!!!!!!!!!!!!!!!!"
![Screenshot_20230612_183756_c](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/72277090/ba523770-1445-40c1-85c3-6d89d71fa55c)

**Comment by gtreshchev** [comment]
Could potentially be fixed by 7056cd6946db9c836db9a5a6a8f7ec089b9139a2, needs testing

**Comment by thesohailirfan** [comment]
The issue still persists and I'm still facing it. It works fine in Android 13 but this issue is seen in Android 11 which returns !!!!!!!!!! as output every time.

**Comment by gtreshchev** [comment]
Will be investigated later, it's hard to say about a particular reason for now. As of now, I recommend using the latest API/NDK/SDK and trying to increase the language model size. Also, use the `SetSuppressBlank`, `SetSuppressNonSpeechTokens` with the `Value` as `true`, and `SetSpeedUp` with the `Value` as false to improve the results.

**Comment by gtreshchev** [comment]
This issue is most likely fixed in efc29beb0518b9e08d7584837e7b67ef9f6b211b, closing this ticket for now. Please reopen it if you still encounter the same issue.
